name: ESlint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd client npm install --production && cd server && npm install -D && npm i -g eslint
    - name: Run ESLint
      run: eslint . --ext .js,.jsx